name: Release artifacts

env:
  # The name of the main module repository
  main_project_module: app
on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'gradle'

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.91.1
          rust-src-dir: ./rust
          target: aarch64-linux-android, wasm32-unknown-unknown

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build fb-android binary and bindings
        working-directory: ./rust/fb-android
        run: ./build-android.sh

      - name: Install debug singing keystore
        env:
          ENCODED_KEY: ${{ secrets.DEBUG_SIGNING_KEY }}
        shell: bash
        run: base64 -di <<< "$ENCODED_KEY" > "./debug.keystore"

      - name: Build apk release project (APK)
        run: ./gradlew assembleRelease

      - name: Build fb-web wasm package
        working-directory: ./rust/fb-web
        run: ./build-web.sh

      - name: Build fb-cli binary
        working-directory: ./rust/fb-cli
        run: cargo build --release

      - name: Publish release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ./app/build/outputs/apk/release/app-release.apk
            ./rust/fb-web/wasm-bundle.zip
            ./rust/target/release/fb-cli
